# Generated by Django 5.2.3 on 2025-07-03 06:33

import ckeditor_uploader.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='about_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='О Компании')),
                ('image', models.ImageField(upload_to='about_company_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='advantage_icons/', verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='article_images/', verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryLuxuryHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория - Роскошный отдых',
                'verbose_name_plural': 'Категории - Роскошного отдыха',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryRealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория - Недвижимость',
                'verbose_name_plural': 'Категории - Недвижимость',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='company_offer_images/', verbose_name='Изображение')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Предложение от компании',
                'verbose_name_plural': 'Предложения от компании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('work_time', models.CharField(max_length=100, verbose_name='Время работы')),
                ('journal_email', models.EmailField(max_length=254, verbose_name='Email (Журнал)')),
                ('pr_email', models.EmailField(max_length=254, verbose_name='Email (PR)')),
                ('hr_email', models.EmailField(max_length=254, verbose_name='Email (HR)')),
                ('index', models.CharField(blank=True, max_length=10, verbose_name='Индекс')),
                ('license_number', models.CharField(blank=True, max_length=20, verbose_name='Лицензия')),
                ('registration_code', models.CharField(blank=True, max_length=20, verbose_name='Регистрационный код')),
                ('facebook_link', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_link', models.URLField(blank=True, verbose_name='Instagram')),
                ('tiktok_link', models.URLField(blank=True, verbose_name='TikTok')),
                ('image', models.ImageField(upload_to='contact_info_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('studio', models.CharField(max_length=255, verbose_name='Студия')),
                ('image', models.ImageField(upload_to='interview_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Интервью',
                'verbose_name_plural': 'Интервью',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='popular_images/', verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Популярное',
                'verbose_name_plural': 'Популярные',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('review', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('firs_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
        ),
        migrations.CreateModel(
            name='LuxuryHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10)),
                ('image', models.ImageField(upload_to='luxury_holiday_images/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luxury_holidays', to='API.categoryluxuryholiday', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Роскошный отдых',
                'verbose_name_plural': 'Роскошный отдых',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10, verbose_name='Язык')),
                ('image', models.ImageField(upload_to='real_estate_images/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estates', to='API.categoryrealestate', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
                'ordering': ['-created_at'],
            },
        ),
    ]
