# Generated by Django 5.2.3 on 2025-07-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='slug',
        ),
    ]
