# Generated by Django 5.2.3 on 2025-07-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_remove_userregistration_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='firs_name',
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='name',
            field=models.CharField(max_length=20, verbose_name='ФИО'),
        ),
    ]
