# Generated by Django 5.2.3 on 2025-06-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_advantage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Luxury_Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория-Росскошный оддых',
                'verbose_name_plural': 'Категории-Росскошных оддыхов',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='luxury_holiday',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='luxury_holidays', to='API.category_luxury_holiday', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
