# Generated by Django 5.2.3 on 2025-07-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_userregistration_firs_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistration',
            options={'ordering': ['-id'], 'verbose_name': 'Регистрация Пользователя', 'verbose_name_plural': 'Регистрации Пользователей'},
        ),
    ]
