# Generated by Django 5.2.3 on 2025-06-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_category_luxury_holiday_luxury_holiday_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Real_Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория-Недвижомость',
                'verbose_name_plural': 'Категории-Недвижимостей',
                'ordering': ['-id'],
            },
        ),
    ]
