# Generated by Django 5.2.3 on 2025-06-28 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_category_real_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='real_estate',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Real_Estate', to='API.category_real_estate', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
