# Generated by Django 5.2.3 on 2025-06-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_real_estate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='image',
            field=models.ImageField(default=1, upload_to='ContactInfo_images/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
