# Generated by Django 5.2.3 on 2025-06-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_contactinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='popular',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular',
            name='title',
            field=models.CharField(default=1, max_length=30, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
