# Generated by Django 5.2.3 on 2025-06-29 14:27

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_popular_text_popular_title_popular_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='О Компании')),
                ('image', models.ImageField(upload_to='about_company_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryLuxuryHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10)),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория - Роскошный отдых',
                'verbose_name_plural': 'Категории - Роскошного отдыха',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryRealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10)),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория - Недвижимость',
                'verbose_name_plural': 'Категории - Недвижимость',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LuxuryHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10)),
                ('image', models.ImageField(upload_to='luxury_holiday_images/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luxury_holidays', to='API.categoryluxuryholiday', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Роскошный отдых',
                'verbose_name_plural': 'Роскошный отдых',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], max_length=10)),
                ('image', models.ImageField(upload_to='real_estate_images/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текст')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estates', to='API.categoryrealestate', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Недвижимость',
                'verbose_name_plural': 'Недвижимость',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='About_Company',
        ),
        migrations.RemoveField(
            model_name='luxury_holiday',
            name='category',
        ),
        migrations.RemoveField(
            model_name='real_estate',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['-created_at'], 'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterModelOptions(
            name='advantage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='companyoffer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Предложение от компании', 'verbose_name_plural': 'Предложения от компании'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Контактная информация', 'verbose_name_plural': 'Контактная информация'},
        ),
        migrations.AlterModelOptions(
            name='popular',
            options={'ordering': ['-created_at'], 'verbose_name': 'Популярное', 'verbose_name_plural': 'Популярные'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='autor',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='object_id',
        ),
        migrations.AddField(
            model_name='about',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advantage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='companyoffer',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], default=11, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='popular',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popular',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='popular',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='review',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('kg', 'Кыргызча')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='about_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='advantage_icons/', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='companyoffer',
            name='image',
            field=models.ImageField(upload_to='company_offer_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='companyoffer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='image',
            field=models.ImageField(upload_to='contact_info_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='popular',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Отзыв'),
        ),
        migrations.DeleteModel(
            name='Category_Luxury_Holiday',
        ),
        migrations.DeleteModel(
            name='Luxury_Holiday',
        ),
        migrations.DeleteModel(
            name='Category_Real_Estate',
        ),
        migrations.DeleteModel(
            name='Real_Estate',
        ),
    ]
