# Generated by Django 5.2.3 on 2025-06-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_aboutcompany_categoryluxuryholiday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryluxuryholiday',
            name='language',
        ),
        migrations.RemoveField(
            model_name='categoryrealestate',
            name='language',
        ),
    ]
